
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button verLexemas;

	private global::Gtk.Entry txtOracion;

	private global::Gtk.Label label1;

	private global::Gtk.Entry txtVista;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Verificador de lexemas");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.verLexemas = new global::Gtk.Button();
		this.verLexemas.CanFocus = true;
		this.verLexemas.Name = "verLexemas";
		this.verLexemas.UseUnderline = true;
		this.verLexemas.Label = global::Mono.Unix.Catalog.GetString("Ver lexemas");
		this.fixed1.Add(this.verLexemas);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.verLexemas]));
		w1.X = 87;
		w1.Y = 81;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtOracion = new global::Gtk.Entry();
		this.txtOracion.CanFocus = true;
		this.txtOracion.Name = "txtOracion";
		this.txtOracion.IsEditable = true;
		this.txtOracion.InvisibleChar = '•';
		this.fixed1.Add(this.txtOracion);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtOracion]));
		w2.X = 240;
		w2.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Escribe aquí la oración");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w3.X = 258;
		w3.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtVista = new global::Gtk.Entry();
		this.txtVista.WidthRequest = 400;
		this.txtVista.HeightRequest = 200;
		this.txtVista.CanFocus = true;
		this.txtVista.Name = "txtVista";
		this.txtVista.IsEditable = false;
		this.txtVista.InvisibleChar = '•';
		this.fixed1.Add(this.txtVista);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtVista]));
		w4.X = 120;
		w4.Y = 224;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 569;
		this.DefaultHeight = 468;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.verLexemas.Clicked += new global::System.EventHandler(this.OnVerLexemasClicked);
	}
}
